# Generated by Django 3.2 on 2023-01-04 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_tag',
            new_name='tag',
        ),
    ]
